#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┏┓┓┏┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┃┃┃ ┃┫ 
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┗┛┗┛┛┗┛
#                                     




# Image Path
$image = /home/riyan/Pictures/Wallpapers/dj0xdez-4eda16a3-692d-470a-a006-31cd013b4e97.gif

# An alpha background
$surface_alpha = rgba(0f15124d)

# All Colors

$background = rgba(0f1512ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2c322eff)

$inverse_primary = rgba(1c6b50ff)

$inverse_surface = rgba(dee4dfff)

$on_background = rgba(dee4dfff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003827ff)

$on_primary_container = rgba(a7f2d0ff)

$on_primary_fixed = rgba(002115ff)

$on_primary_fixed_variant = rgba(00513aff)

$on_secondary = rgba(1f352bff)

$on_secondary_container = rgba(cfe9daff)

$on_secondary_fixed = rgba(092017ff)

$on_secondary_fixed_variant = rgba(354b41ff)

$on_surface = rgba(dee4dfff)

$on_surface_variant = rgba(bfc9c2ff)

$on_tertiary = rgba(093544ff)

$on_tertiary_container = rgba(c2e8fcff)

$on_tertiary_fixed = rgba(001f2aff)

$on_tertiary_fixed_variant = rgba(254b5cff)

$outline = rgba(89938dff)

$outline_variant = rgba(404944ff)

$primary = rgba(8bd5b5ff)

$primary_container = rgba(00513aff)

$primary_fixed = rgba(a7f2d0ff)

$primary_fixed_dim = rgba(8bd5b5ff)

$scrim = rgba(000000ff)

$secondary = rgba(b3ccbfff)

$secondary_container = rgba(354b41ff)

$secondary_fixed = rgba(cfe9daff)

$secondary_fixed_dim = rgba(b3ccbfff)

$shadow = rgba(000000ff)

$source_color = rgba(7b9e8dff)

$surface = rgba(0f1512ff)

$surface_bright = rgba(343b37ff)

$surface_container = rgba(1b211eff)

$surface_container_high = rgba(252b28ff)

$surface_container_highest = rgba(303633ff)

$surface_container_low = rgba(171d1aff)

$surface_container_lowest = rgba(0a0f0dff)

$surface_dim = rgba(0f1512ff)

$surface_tint = rgba(8bd5b5ff)

$surface_variant = rgba(404944ff)

$tertiary = rgba(a6cce0ff)

$tertiary_container = rgba(254b5cff)

$tertiary_fixed = rgba(c2e8fcff)

$tertiary_fixed_dim = rgba(a6cce0ff)

